//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMWU.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultGMadFilePath {
            get {
                return ((string)(this["DefaultGMadFilePath"]));
            }
            set {
                this["DefaultGMadFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultGMPublishFilePath {
            get {
                return ((string)(this["DefaultGMPublishFilePath"]));
            }
            set {
                this["DefaultGMPublishFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AddonFolderLocation {
            get {
                return ((string)(this["AddonFolderLocation"]));
            }
            set {
                this["AddonFolderLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GMadFile1Location {
            get {
                return ((string)(this["GMadFile1Location"]));
            }
            set {
                this["GMadFile1Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GMadOutputLocation {
            get {
                return ((string)(this["GMadOutputLocation"]));
            }
            set {
                this["GMadOutputLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExtractOutputLocation {
            get {
                return ((string)(this["ExtractOutputLocation"]));
            }
            set {
                this["ExtractOutputLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GMadFile2Location {
            get {
                return ((string)(this["GMadFile2Location"]));
            }
            set {
                this["GMadFile2Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GMAFile1Location {
            get {
                return ((string)(this["GMAFile1Location"]));
            }
            set {
                this["GMAFile1Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GMAFile2Location {
            get {
                return ((string)(this["GMAFile2Location"]));
            }
            set {
                this["GMAFile2Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GMPubFile1Location {
            get {
                return ((string)(this["GMPubFile1Location"]));
            }
            set {
                this["GMPubFile1Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IconFile1Location {
            get {
                return ((string)(this["IconFile1Location"]));
            }
            set {
                this["IconFile1Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GMAFile3Location {
            get {
                return ((string)(this["GMAFile3Location"]));
            }
            set {
                this["GMAFile3Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GMPubFile2Location {
            get {
                return ((string)(this["GMPubFile2Location"]));
            }
            set {
                this["GMPubFile2Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UpdateAddonID {
            get {
                return ((int)(this["UpdateAddonID"]));
            }
            set {
                this["UpdateAddonID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UpdateAddonNotes {
            get {
                return ((string)(this["UpdateAddonNotes"]));
            }
            set {
                this["UpdateAddonNotes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IconFile2Location {
            get {
                return ((string)(this["IconFile2Location"]));
            }
            set {
                this["IconFile2Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GMPubFile3Location {
            get {
                return ((string)(this["GMPubFile3Location"]));
            }
            set {
                this["GMPubFile3Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UpdateIconID {
            get {
                return ((int)(this["UpdateIconID"]));
            }
            set {
                this["UpdateIconID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TaskName {
            get {
                return ((string)(this["TaskName"]));
            }
            set {
                this["TaskName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TaskNotes {
            get {
                return ((string)(this["TaskNotes"]));
            }
            set {
                this["TaskNotes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainControlIndex {
            get {
                return ((int)(this["MainControlIndex"]));
            }
            set {
                this["MainControlIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TaskControlIndex {
            get {
                return ((int)(this["TaskControlIndex"]));
            }
            set {
                this["TaskControlIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ConsoleControlIndex {
            get {
                return ((int)(this["ConsoleControlIndex"]));
            }
            set {
                this["ConsoleControlIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TaskSelectionIndex {
            get {
                return ((int)(this["TaskSelectionIndex"]));
            }
            set {
                this["TaskSelectionIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultGMadLocation {
            get {
                return ((string)(this["DefaultGMadLocation"]));
            }
            set {
                this["DefaultGMadLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultGMPubLocation {
            get {
                return ((string)(this["DefaultGMPubLocation"]));
            }
            set {
                this["DefaultGMPubLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseDefaultLocations {
            get {
                return ((bool)(this["UseDefaultLocations"]));
            }
            set {
                this["UseDefaultLocations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30000")]
        public int TaskIntervalTime {
            get {
                return ((int)(this["TaskIntervalTime"]));
            }
            set {
                this["TaskIntervalTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoRunTasks {
            get {
                return ((bool)(this["AutoRunTasks"]));
            }
            set {
                this["AutoRunTasks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string JsonFileOutput {
            get {
                return ((string)(this["JsonFileOutput"]));
            }
            set {
                this["JsonFileOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string JsonAddonTitle {
            get {
                return ((string)(this["JsonAddonTitle"]));
            }
            set {
                this["JsonAddonTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string JsonAddonWildcards {
            get {
                return ((string)(this["JsonAddonWildcards"]));
            }
            set {
                this["JsonAddonWildcards"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AddonTag1Index {
            get {
                return ((int)(this["AddonTag1Index"]));
            }
            set {
                this["AddonTag1Index"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AddonTag2Index {
            get {
                return ((int)(this["AddonTag2Index"]));
            }
            set {
                this["AddonTag2Index"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AddonTypeIndex {
            get {
                return ((int)(this["AddonTypeIndex"]));
            }
            set {
                this["AddonTypeIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GMAFileName {
            get {
                return ((string)(this["GMAFileName"]));
            }
            set {
                this["GMAFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int ChangeTaskTime {
            get {
                return ((int)(this["ChangeTaskTime"]));
            }
            set {
                this["ChangeTaskTime"] = value;
            }
        }
    }
}
